#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_asterisk(opsys, conf, conf_dir, plugins_dir):
    if opsys == "linux":
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/asterisk", plugins_dir + "/asterisk")

bakery_info["asterisk"] = {
    "bake_function" : bake_asterisk,
    "os"            : [ "linux" ],
}
