#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 2 -*-

# (c) 2019 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_asterisk_channels(info):
  if len(info) > 1:
    yield (None, {})

def check_asterisk_channels(_no_item, _no_params, info):
  if len(info) > 1:
    for line in info:
      if line == [u'Channel', u'Location', u'State', u'Application(Data)']:
        continue
      if len(line) == 4:
        if line[2] != u'Up':
          yield 2, "Channel %s is %s" % (line[0], line[2])
      if len(line) == 3:
        text = " ".join(line[1:])
        metric = "_".join(line[1:])
        value = saveint(line[0])
        if metric == 'calls_processed':
          value = get_rate('asterisk_channels.%s' % metric, time.time(), value)
        yield 0, "%d %s" % (value, text), [(metric, value)]

check_info['asterisk_channels'] = {
  'inventory_function' : inventory_asterisk_channels,
  'check_function'     : check_asterisk_channels,
  'service_description': 'Asterisk Channels',
  'has_perfdata'       : True,
}
