#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 2 -*-

check_default_levels["asterisk_iax2_peers"] = "asterisk_peers_default_levels"

factory_settings["asterisk_peers_default_levels"] = {
  "asteriskPeerLatency" : (1500, 2000)
}

#def inventory_asterisk_peers(info):
#  for line in info:
#    host = line[0]
#    yield host, None

def inventory_asterisk_iax2_peers(info):
  for line in info:
    peer = line[0]
    host = line[1]
    other = line[2]
    status = line[4]
    latency = line[5]
    yield host, None


def check_asterisk_iax2_peers(item, params, info):

  # Get warn/crit values
  asteriskPeerLatencyparams = params.get("asteriskPeerLatency")
  if asteriskPeerLatencyparams == None:
    asteriskPeerLatencywarn, asteriskPeerLatencycrit = None, None
  else:
    asteriskPeerLatencywarn, asteriskPeerLatencycrit = asteriskPeerLatencyparams

  for line in info:
    perfdata = [ ( "asteriskPeerLatency", saveint(line[5]), asteriskPeerLatencywarn, asteriskPeerLatencycrit ) ]
    if line[4] == "OK":
      return (0, "State is %s, latency is %dms" % (line[4], saveint(line[5])), perfdata)
    else:
      return (2, "State is %s (!!)" % line[4], perfdata)

  return (3, "UNKNOWN - item not found in snmp data")

check_info['asterisk_iax2_peers'] = (check_asterisk_iax2_peers, "Asterisk peer %s", 1, inventory_asterisk_iax2_peers)
